
twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    cache: false

    globals:
        uuid: '@App\Controller\CartController'

when@test:
    twig:
        strict_variables: true

