vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        covers:
            uri_prefix: /imgs/covers
            upload_destination: '%kernel.project_dir%/public/upload/imgs/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
